FROM node:20-alpine AS base
WORKDIR /app

COPY package.json package-lock.json turbo.json ./
COPY apps/web/package.json apps/web/package.json

RUN npm install --workspace apps/web --include-workspace-root

COPY apps/web apps/web

RUN npm run build --workspace apps/web

EXPOSE 3000
CMD ["npm", "run", "start", "--workspace", "apps/web"]
